---
- name: "{{ ansible_facts['distribution']}} | pipewire | Checking for distro config..."
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yaml"
  register: distribution_config

- name: "{{ ansible_facts['distribution']}} | pipewire | Running tasks..."
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yaml"
  when: distribution_config.stat.exists