---
- name: "{{ ansible_facts['distribution']}} | GPU DRIVERS | Checking for {{ gpu_vendor}} vendor config..."
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}_{{ gpu_vendor }}.yaml"
  register: distribution_config

- name: "{{ ansible_facts['distribution']}} | GPU DRIVERS | Running tasks..."
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}_{{ gpu_vendor }}.yaml"
  when: distribution_config.stat.exists